
package com.mycompany.sisam.cidades;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CidadesService", targetNamespace = "http://sisam.cptec.inpe.br/sisam_webservice/services/CidadesWebService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CidadesService {


    /**
     * 
     * @param cidade
     * @return
     *     returns java.util.List<com.mycompany.sisam.cidades.PontosMunicipais>
     */
    @WebMethod
    @WebResult(name = "getMunicipiosReturn", targetNamespace = "http://webservice.sisam.dsa.inpe.br")
    @RequestWrapper(localName = "getMunicipios", targetNamespace = "http://webservice.sisam.dsa.inpe.br", className = "com.mycompany.sisam.cidades.GetMunicipios")
    @ResponseWrapper(localName = "getMunicipiosResponse", targetNamespace = "http://webservice.sisam.dsa.inpe.br", className = "com.mycompany.sisam.cidades.GetMunicipiosResponse")
    public List<PontosMunicipais> getMunicipios(
        @WebParam(name = "cidade", targetNamespace = "http://webservice.sisam.dsa.inpe.br")
        String cidade);

    /**
     * 
     * @return
     *     returns java.util.List<com.mycompany.sisam.cidades.Estados>
     */
    @WebMethod
    @WebResult(name = "getEstadosReturn", targetNamespace = "http://webservice.sisam.dsa.inpe.br")
    @RequestWrapper(localName = "getEstados", targetNamespace = "http://webservice.sisam.dsa.inpe.br", className = "com.mycompany.sisam.cidades.GetEstados")
    @ResponseWrapper(localName = "getEstadosResponse", targetNamespace = "http://webservice.sisam.dsa.inpe.br", className = "com.mycompany.sisam.cidades.GetEstadosResponse")
    public List<Estados> getEstados();

}
