
package com.mycompany.sisam.mesano;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * 
 * Lista meses e anos disponiveis para a consulta agregada  
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "MesAnoServiceService", targetNamespace = "http://sisam.cptec.inpe.br/sisam_webservice/services/MesAnoWebService", wsdlLocation = "http://sisam.cptec.inpe.br/sisam_webservice/services/MesAnoWebService?wsdl")
public class MesAnoServiceService
    extends Service
{

    private final static URL MESANOSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException MESANOSERVICESERVICE_EXCEPTION;
    private final static QName MESANOSERVICESERVICE_QNAME = new QName("http://sisam.cptec.inpe.br/sisam_webservice/services/MesAnoWebService", "MesAnoServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://sisam.cptec.inpe.br/sisam_webservice/services/MesAnoWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MESANOSERVICESERVICE_WSDL_LOCATION = url;
        MESANOSERVICESERVICE_EXCEPTION = e;
    }

    public MesAnoServiceService() {
        super(__getWsdlLocation(), MESANOSERVICESERVICE_QNAME);
    }

    public MesAnoServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns MesAnoService
     */
    @WebEndpoint(name = "MesAnoWebService")
    public MesAnoService getMesAnoWebService() {
        return super.getPort(new QName("http://sisam.cptec.inpe.br/sisam_webservice/services/MesAnoWebService", "MesAnoWebService"), MesAnoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MesAnoService
     */
    @WebEndpoint(name = "MesAnoWebService")
    public MesAnoService getMesAnoWebService(WebServiceFeature... features) {
        return super.getPort(new QName("http://sisam.cptec.inpe.br/sisam_webservice/services/MesAnoWebService", "MesAnoWebService"), MesAnoService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MESANOSERVICESERVICE_EXCEPTION!= null) {
            throw MESANOSERVICESERVICE_EXCEPTION;
        }
        return MESANOSERVICESERVICE_WSDL_LOCATION;
    }

}
